# Generated by Django 5.1.7 on 2025-04-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benvoplanify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benevole',
            name='mot_de_passe',
        ),
    ]
